palpiteiro:
  outputs:
    dev:
      dataset: cartola
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ./keyfile.json
      location: us-east4
      method: service-account
      priority: interactive
      project: palpiteiro-dev
      threads: 4
      type: bigquery
  target: dev
