Pipeline:
  steps:
  - - columntransformer
    - ColumnTransformer:
        remainder: passthrough
        transformers:
        - - onehotencoder
          - OrdinalEncoder:
              handle_unknown: use_encoded_value
              unknown_value: -1
          - - 0
  - - histgradientboostingregressor
    - HistGradientBoostingRegressor:
        categorical_features:
        - 0
        l2_regularization: 0.0010164605362679774
        learning_rate: 0.05188952180319335
        loss: poisson
        max_bins: 185
        max_depth: 63
        max_iter: 233
        max_leaf_nodes: 369
        min_samples_leaf: 328
