Pipeline:
  steps:
  - - columntransformer
    - ColumnTransformer:
        remainder:
          PowerTransformer: null
        transformers:
        - - onehotencoder
          - OneHotEncoder:
              handle_unknown: ignore
              sparse: false
          - - 0
  - - histgradientboostingregressor
    - HistGradientBoostingRegressor:
        l2_regularization: 3.9166747755750437
        learning_rate: 0.055142950779143364
        loss: poisson
        max_bins: 173
        max_depth: 34
        max_iter: 230
        max_leaf_nodes: 1051
        min_samples_leaf: 289
