SELECT
    id,
    player,
    round,
    season,
    club,
    position,
    status,
    points,
    price,
    variation,
    mean,
    matches,
    COALESCE(goal - LAG(goal) OVER(PARTITION BY player, season ORDER BY round), goal) AS goal,
    COALESCE(assist - LAG(assist) OVER(PARTITION BY player, season ORDER BY round), assist) AS assist,
    COALESCE(yellow_card - LAG(yellow_card) OVER(PARTITION BY player, season ORDER BY round), yellow_card) AS yellow_card,
    COALESCE(red_card - LAG(red_card) OVER(PARTITION BY player, season ORDER BY round), red_card) AS red_card,
    COALESCE(missed_shoot - LAG(missed_shoot) OVER(PARTITION BY player, season ORDER BY round), missed_shoot) AS missed_shoot,
    COALESCE(on_post_shoot - LAG(on_post_shoot) OVER(PARTITION BY player, season ORDER BY round), on_post_shoot) AS on_post_shoot,
    COALESCE(saved_shoot - LAG(saved_shoot) OVER(PARTITION BY player, season ORDER BY round), saved_shoot) AS saved_shoot,
    COALESCE(received_foul - LAG(received_foul) OVER(PARTITION BY player, season ORDER BY round), received_foul) AS received_foul,
    COALESCE(received_penalty - LAG(received_penalty) OVER(PARTITION BY player, season ORDER BY round), received_penalty) AS received_penalty,
    COALESCE(missed_penalty - LAG(missed_penalty) OVER(PARTITION BY player, season ORDER BY round), missed_penalty) AS missed_penalty,
    COALESCE(outside - LAG(outside) OVER(PARTITION BY player, season ORDER BY round), outside) AS outside,
    COALESCE(missed_pass - LAG(missed_pass) OVER(PARTITION BY player, season ORDER BY round), missed_pass) AS missed_pass,
    COALESCE(tackle - LAG(tackle) OVER(PARTITION BY player, season ORDER BY round), tackle) AS tackle,
    COALESCE(foul - LAG(foul) OVER(PARTITION BY player, season ORDER BY round), foul) AS foul,
    COALESCE(penalty - LAG(penalty) OVER(PARTITION BY player, season ORDER BY round), penalty) AS penalty,
    COALESCE(own_goal - LAG(own_goal) OVER(PARTITION BY player, season ORDER BY round), own_goal) AS own_goal,
    COALESCE(allowed_goal - LAG(allowed_goal) OVER(PARTITION BY player, season ORDER BY round), allowed_goal) AS allowed_goal,
    COALESCE(no_goal - LAG(no_goal) OVER(PARTITION BY player, season ORDER BY round), no_goal) AS no_goal,
    COALESCE(save - LAG(save) OVER(PARTITION BY player, season ORDER BY id), save) AS save,
    COALESCE(difficult_save - LAG(difficult_save) OVER(PARTITION BY player, season ORDER BY round), difficult_save) AS difficult_save,
    COALESCE(penalty_save - LAG(penalty_save) OVER(PARTITION BY player, season ORDER BY round), penalty_save) AS penalty_save,
FROM
    {{ stg_atletas_scoring }}