name: aws-main
on:
  push:
    branches:
      - main
    paths:
      - "lambda_*/**"
      - "utils/**"
      - "requirements-bigquery.txt"
      - "requirements-pandas.txt"
      - "serverless.yml"
      - ".github/workflows/aws.yml"
      - ".github/workflows/aws_main.yml"
  workflow_dispatch:
jobs:
  aws:
    uses: ./.github/workflows/aws.yml
    with:
      STAGE: main
    secrets:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
      GCP_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.GCP_SERVICE_ACCOUNT_PROJECT_ID_MAIN }}
      GCP_SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.GCP_SERVICE_ACCOUNT_PRIVATE_KEY_ID_MAIN }}
      GCP_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_PRIVATE_KEY_MAIN }}
      GCP_SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_CLIENT_EMAIL_MAIN }}
      GCP_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.GCP_SERVICE_ACCOUNT_CLIENT_ID_MAIN }}
      GCP_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL: ${{ secrets.GCP_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL_MAIN }}
      GLBID: ${{ secrets.GLBID }}
      THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}