name: dbt
on:
  push:
    branches:
      - main
    paths:
      - "dbt/**"
      - ".github/workflows/dbt.yml"
      - ".github/workflows/dbt_main.yml"
  workflow_dispatch:
jobs:
  dbt:
    uses: ./.github/workflows/dbt.yml
    with:
      TARGET: main
    secrets:
      GCP_KEYFILE: ${{ secrets.GCP_KEYFILE_MAIN }}