name: Deployment
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Serverless Framework
        run: |
          npm install -g serverless@3
          npm install --save-dev serverless-step-functions
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Create layers artifacts
        run: |
          mkdir python
          pip install -r requirements-pandas.txt --target python
          zip -r layer_pandas.zip python/
          rm -r python
          mkdir python
          pip install -r requirements-bigquery.txt --target python
          zip -r layer_bigguery.zip python/
          rm -r python
      - name: Deploy
        run: sls deploy --stage ${{ github.head_ref || github.ref_name }}
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          OPTIONS: ${{ secrets.OPTIONS }}
