name: DBT Deployment
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud dev environment
        if: github.head_ref == 'dev' || github.ref_name == 'dev'
        uses: 'google-github-actions/auth@v0.7.1'
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE_DEV }}
      - name: Authenticate to Google Cloud main environment
        if: github.head_ref == 'main' || github.ref_name == 'main'
        uses: 'google-github-actions/auth@v0.7.1'
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE_MAIN }}
      - name: Setup Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install DBT
        run: |
          pip install --upgrade pip wheel
          pip install dbt-bigquery
      - name: Deploy Seeds
        run: dbt seed --profiles-dir .
      - name: Deploy Models
        run: dbt run --profiles-dir .
        working-directory: ./dbt
      - name: Test
        run: dbt test --profiles-dir .
        working-directory: ./dbt
