name: gcp
on:
  workflow_call:
    inputs:
      FUNCTION_NAME:
        required: true
        type: string
      BUCKET_NAME:
        required: true
        type: string
    secrets:
      GCP_KEYFILE:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: authenticate
        uses: "google-github-actions/auth@v0.7.1"
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}
      - id: deploy
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: ${{ inputs.FUNCTION_NAME }}
          runtime: python39
          memory_mb: 512
          entry_point: handler
          region: us-east4
          source_dir: function_points
          env_vars: "BUCKET_NAME=${{ inputs.BUCKET_NAME }}"
