name: Quality Assurance
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder:
          - lambda_draft
          - lambda_extract_cartola_matches
          - lambda_extract_cartola_players
          - lambda_extract_fivethirtyeight_spi
          - lambda_forecast
          - lambda_load
          - lambda_transform_cartola_matches
          - lambda_transform_cartola_players
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install pylint pytest
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./${{ matrix.folder }}
      - name: Linting with Pylint
        run: pylint ${{ matrix.folder }}